# Generated by Django 4.1.7 on 2023-03-01 17:40

from django.db import migrations, models
import django.db.models.deletion
import main_page.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=255, verbose_name='Текст заголовка')),
                ('desc', models.TextField(max_length=1000, verbose_name='Опис')),
                ('tab', models.CharField(max_length=55, verbose_name='Текст кнопки')),
                ('user', models.CharField(max_length=55, verbose_name="Ім'я засновника")),
                ('pos_user', models.CharField(max_length=55, verbose_name='Посада')),
                ('img_user', models.ImageField(upload_to=main_page.utils.get_file_name, verbose_name='Зображення засновника')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимість')),
                ('img_1', models.ImageField(upload_to=main_page.utils.get_file_name, verbose_name='Зображення дитини')),
                ('img_2', models.ImageField(upload_to=main_page.utils.get_file_name, verbose_name='Зображення дитини')),
                ('img_3', models.ImageField(upload_to=main_page.utils.get_file_name, verbose_name='Зображення дитини')),
            ],
            options={
                'verbose_name_plural': 'Ми про нас',
                'ordering': ('h1',),
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('child_name', models.CharField(max_length=50)),
                ('child_age', models.SmallIntegerField()),
                ('message', models.TextField(blank=True, max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('date_processing', models.DateField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Призначити зустріч',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заговок')),
                ('desc', models.TextField(blank=True, max_length=500, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to=main_page.utils.get_file_name, verbose_name='Зображення')),
                ('position', models.SmallIntegerField(unique=True, verbose_name='Позиція')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимість')),
                ('tab_1', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки')),
                ('tab_1_url', models.URLField(blank=True, verbose_name='Посилання')),
            ],
            options={
                'verbose_name_plural': 'Заклик',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=50, verbose_name='Заговок')),
                ('address', models.CharField(max_length=50, verbose_name='Адреса')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.CharField(max_length=50, verbose_name='Пошта')),
                ('twi_url', models.URLField(blank=True, verbose_name='Посилання на twitter')),
                ('fb_url', models.URLField(blank=True, verbose_name='Посилання на facebook')),
                ('youtube_url', models.URLField(blank=True, verbose_name='Посилання на youtube')),
                ('in_url', models.URLField(blank=True, verbose_name='Посилання на LinkedIn')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Наші контакти',
                'ordering': ('h1',),
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, max_length=250)),
                ('subject', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('date_processing', models.DateField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': "Зворотній зв'язок",
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1_col_1', models.CharField(max_length=50, verbose_name='Назва колонка №1')),
                ('desc_col_1', models.TextField(max_length=255, verbose_name='Опис колонка №1')),
                ('h1_col_2', models.CharField(max_length=50, verbose_name='Назва колонка №2')),
                ('desc_col_2', models.TextField(max_length=255, verbose_name='Опис колонка №2')),
                ('h1_col_3', models.CharField(max_length=50, verbose_name='Назва колонка №3')),
                ('desc_col_3', models.TextField(max_length=255, verbose_name='Опис колонка №3')),
                ('h1_col_4', models.CharField(max_length=50, verbose_name='Назва колонка №4')),
                ('desc_col_4', models.TextField(max_length=255, verbose_name='Опис колонка №4')),
                ('position', models.SmallIntegerField(unique=True, verbose_name='Позиція')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимість')),
            ],
            options={
                'verbose_name_plural': 'Шкільні зручності',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=main_page.utils.get_file_name, verbose_name='Зображення')),
                ('position', models.SmallIntegerField(unique=True, verbose_name='Позиція')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимість')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Галерея',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Headlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_facilities', models.CharField(max_length=50, verbose_name='Заговок facilities')),
                ('desc_facilities', models.TextField(blank=True, max_length=500, verbose_name='Текст facilities')),
                ('title_classes', models.CharField(max_length=50, verbose_name='Заговок classes')),
                ('desc_classes', models.TextField(blank=True, max_length=500, verbose_name='Текст classes ')),
                ('title_teachers', models.CharField(max_length=50, verbose_name='Заговок teachers')),
                ('desc_teachers', models.TextField(blank=True, max_length=500, verbose_name='Текст teachers')),
                ('title_testimonial', models.CharField(max_length=50, verbose_name='Заговок testimonial')),
                ('desc_testimonial', models.TextField(blank=True, max_length=500, verbose_name='Текст testimonial')),
            ],
            options={
                'verbose_name_plural': 'Заголовки',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заговок')),
                ('desc', models.TextField(blank=True, max_length=500, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to=main_page.utils.get_file_name, verbose_name='Зображення')),
                ('position', models.SmallIntegerField(unique=True, verbose_name='Позиція')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимість')),
            ],
            options={
                'verbose_name_plural': 'Розклад занять',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва слайду')),
                ('position', models.SmallIntegerField(unique=True, verbose_name='Позиція')),
                ('image', models.ImageField(upload_to=main_page.utils.get_file_name, verbose_name='Зображення')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимість')),
                ('h_1', models.CharField(blank=True, max_length=250, verbose_name='Заголовок')),
                ('desc', models.TextField(blank=True, max_length=500, verbose_name='Опис')),
                ('tab_1', models.CharField(blank=True, max_length=50, verbose_name='Назва кнопки 1')),
                ('tab_1_url', models.URLField(blank=True, verbose_name='Посилання 1')),
                ('tab_2', models.CharField(blank=True, max_length=50, verbose_name='Назва кнопки 1')),
                ('tab_2_url', models.URLField(blank=True, verbose_name='Посилання 2')),
            ],
            options={
                'verbose_name_plural': 'Слайдер',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(auto_now_add=True)),
                ('date_processing', models.DateField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Підписка на email розсилку',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Повне ім'я")),
                ('profession', models.TextField(max_length=50, verbose_name='Посада')),
                ('position', models.SmallIntegerField(unique=True, verbose_name='Позиція')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимість')),
                ('image', models.ImageField(blank=True, upload_to=main_page.utils.get_file_name, verbose_name='Фото')),
                ('desc', models.TextField(blank=True, max_length=500, verbose_name='Посада')),
                ('image_clas', models.ImageField(blank=True, upload_to=main_page.utils.get_file_name, verbose_name='Фото клас')),
                ('twi_url', models.URLField(blank=True, default='https://twitter.com/', verbose_name='Посилання на twitter')),
                ('fb_url', models.URLField(blank=True, default='https://www.facebook.com/', verbose_name='Посилання на facebook')),
                ('in_url', models.URLField(blank=True, default='https://www.instagram.com/', verbose_name='Посилання на instagram')),
            ],
            options={
                'verbose_name_plural': 'Наша команда',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Повне ім'я")),
                ('profession', models.TextField(max_length=50, verbose_name='Посада')),
                ('position', models.SmallIntegerField(unique=True, verbose_name='Позиція')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимість')),
                ('image', models.ImageField(blank=True, upload_to=main_page.utils.get_file_name, verbose_name='Фото')),
                ('desc', models.TextField(blank=True, max_length=500, verbose_name='Текст')),
            ],
            options={
                'verbose_name_plural': 'Відгуки',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ціна')),
                ('image', models.ImageField(blank=True, upload_to=main_page.utils.get_file_name, verbose_name='Фото')),
                ('position', models.SmallIntegerField(unique=True, verbose_name='Позиція')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимість')),
                ('age', models.CharField(default='3-5 Years', max_length=50, verbose_name='Вік')),
                ('time', models.CharField(default='9-10 AM', max_length=50, verbose_name='Час початку занять')),
                ('capacity', models.CharField(default='30 Kids', max_length=50, verbose_name='Кількість в групі')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='main_page.team')),
            ],
            options={
                'verbose_name_plural': 'Класи',
                'ordering': ('position',),
            },
        ),
    ]
